### ISSUE TITLE
Nodejs 6 not supported ?

### ISSUE THREAD

**Issue by daslicht** [JumpLinkNetwork/jumplink-october-boilerplate#1]
Hi,
when I run `npm run theme_settings` in the themes root i get : 

$ npm run theme_settings

> jumplink-october-boilerplate@1.0.1 theme_settings /srv/users/serverpilot/apps/ansolas/public/themes/jumplink-october-boilerplate
> node ./utilities/bootstrap_theme_settings.js && node ./utilities/merge_theme_settings.js

module.js:457
    throw err;
    ^

Error: Cannot find module 'write-yaml'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/users/serverpilot/apps/ansolas/public/themes/jumplink-october-boilerplate/utilities/bootstrap_theme_settings.js:2:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "theme_settings"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! jumplink-october-boilerplate@1.0.1 theme_settings: `node ./utilities/bootstrap_theme_settings.js && node ./utilities/merge_theme_settings.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jumplink-october-boilerplate@1.0.1 theme_settings script 'node ./utilities/bootstrap_theme_settings.js && node ./utilities/merge_theme_settings.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jumplink-october-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./utilities/bootstrap_theme_settings.js && node ./utilities/merge_theme_settings.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jumplink-october-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jumplink-october-boilerplate
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/users/serverpilot/apps/ansolas/public/themes/jumplink-october-boilerplate/npm-debug.log
serverpilot@v22015072938226788:~/apps/ansolas/public/themes/jumplink-october-boilerplate$ 

```

idea?
```

**Comment by daslicht** [comment]
just installed node 5 via nvm, same result

**Comment by daslicht** [comment]
I think I've identified the source of error:

https://github.com/daslicht/jumplink-october-boilerplate/commits/master

**Comment by JumpLink** [comment]
If you wan'a change variables or other core stuff you need to install all dependencies with

```
bower install
npm install
```

Please not, there is a known issue with `default: 0` values, the this for more details: https://github.com/octobercms/october/issues/2388
